require("options")
require("keymaps")
require("autocommands")
require("launch")
spec("whichkey")

spec("user.ui.colorscheme")
spec("user.ui.devicons")
spec("user.ui.nvimtree")
spec("user.ui.alpha")
spec("user.ui.telescope")
spec("user.ui.barbar")
spec("user.ui.lualine")
spec("user.ui.incline")
spec("user.ui.vim-maximizer")
spec("user.ui.vim-tmux-navigator")
spec("user.ui.nvim-notify")
spec("user.ui.noice")
spec("user.editor.sessions")
spec("user.editor.workspaces")
-- spec("user.editor.project")
spec("user.editor.mini-ai")
spec("user.editor.mini-align")
spec("user.editor.mini-cursorword")
spec("user.editor.mini-operators")
spec("user.editor.comment")
spec("user.editor.todo-comments")
spec("user.editor.mini-pairs")
spec("user.editor.indentline")
spec("user.editor.undotree")
spec("user.editor.nvim-surround")
spec("user.editor.macros")
spec("user.editor.mini-trailspace")
spec("user.editor.mini-move")
spec("user.editor.vim-just")
spec("user.utils.toggleterm")


spec("user.coding.treesitter")
spec("user.ui.twilight")
spec("user.coding.mason")
spec("user.coding.lspconfig")
spec("user.coding.cmp")
spec("user.coding.none-ls")
spec("user.coding.symbols-outline")
spec("user.coding.inc-rename")

require("user.lazy")
